# Generated by Django 4.0.7 on 2022-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_alter_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='offeredprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
