# Generated by Django 4.0.7 on 2022-09-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_stock_offeredprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='offeredprice',
        ),
    ]
