# Generated by Django 4.0.7 on 2022-09-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_remove_stock_offeredprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='subcatname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.subcategory'),
        ),
    ]
