# Generated by Django 4.0.7 on 2022-10-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0006_stock_prooffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image4',
            field=models.ImageField(upload_to=''),
        ),
    ]
