# Generated by Django 4.0.7 on 2022-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0007_alter_stock_image1_alter_stock_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image1',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image2',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image3',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image4',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
