# Generated by Django 4.0.7 on 2022-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.AddField(
            model_name='address',
            name='Housename1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='city1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='city2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='district1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='district2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='housename',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
