# Generated by Django 4.0.7 on 2022-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0005_remove_address_housename1_remove_address_city2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='method',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
