# Generated by Django 4.0.7 on 2022-09-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0006_myorders_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='orderstatus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
