# Generated by Django 4.0.7 on 2022-09-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0011_remove_myorders_address1_remove_myorders_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moreAdmin.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myorders',
            name='name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
