# Generated by Django 4.0.7 on 2022-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0013_myorders_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='orderdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
