# Generated by Django 4.0.7 on 2022-09-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0015_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='orderid',
        ),
        migrations.AddField(
            model_name='myorders',
            name='orderid',
            field=models.BigIntegerField(default=1),
        ),
    ]
