# Generated by Django 4.0.7 on 2022-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0016_remove_payment_orderid_myorders_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderid',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='True', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='orderid',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
