# Generated by Django 4.0.7 on 2022-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0018_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
