# Generated by Django 4.0.7 on 2022-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0019_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
