# Generated by Django 4.0.7 on 2022-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreAdmin', '0020_alter_coupon_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
