# Generated by Django 4.0.7 on 2022-09-20 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
