# Generated by Django 4.0.7 on 2022-09-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='userid',
        ),
    ]
