# Generated by Django 4.0.7 on 2022-09-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartmanagement', '0004_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
